spring.application.name=smart-college-erp
spring.datasource.url=jdbc:mysql://localhost:3306/smart_college_erp
spring.datasource.username=root
spring.datasource.password=Sachin@16

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=MySuperSecretKeyForSmartCollegeERP2026